Fix TestFlight error: Add NSPhotoLibraryUsageDescription to Info.plist
Apple requires this permission string even though the app doesn't
actively use photo library. Required by app dependencies (WebView, etc.)

Error: 90683 - Missing purpose string in Info.plist